# Generated by Django 5.0.7 on 2024-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo4app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_type', models.CharField(max_length=40)),
                ('p_address', models.CharField(max_length=100)),
                ('d_address', models.CharField(max_length=100)),
                ('product_detail', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'cust_order',
                'managed': False,
            },
        ),
    ]
