# Generated by Django 5.0.7 on 2024-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo4app', '0002_custorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookorder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_type', models.CharField(max_length=40)),
                ('p_city', models.CharField(max_length=40)),
                ('d_city', models.CharField(max_length=40)),
                ('producy_image', models.TextField(blank=True, null=True)),
                ('product_detail', models.CharField(max_length=400)),
                ('pay_type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'bookorder',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustOrder',
        ),
    ]
