# Generated by Django 5.0.7 on 2024-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo4app', '0003_bookorder_delete_custorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('truckid', models.AutoField(db_column='TruckID', primary_key=True, serialize=False)),
                ('trucktype', models.CharField(blank=True, db_column='TruckType', max_length=50, null=True)),
                ('lengthft', models.IntegerField(blank=True, db_column='LengthFT', null=True)),
                ('widthft', models.DecimalField(blank=True, db_column='WidthFT', decimal_places=1, max_digits=4, null=True)),
                ('heightft', models.DecimalField(blank=True, db_column='HeightFT', decimal_places=1, max_digits=4, null=True)),
                ('maxloadtons', models.DecimalField(blank=True, db_column='MaxLoadTons', decimal_places=2, max_digits=5, null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
            ],
            options={
                'db_table': 'trucks',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bookorder',
        ),
    ]
