# Generated by Django 5.0.7 on 2024-08-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo4app', '0004_trucks_delete_bookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.BigAutoField(db_column='Book_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('pick_address', models.CharField(max_length=100)),
                ('deliver_address', models.CharField(max_length=100)),
                ('product_image', models.TextField(blank=True, null=True)),
                ('product_detail', models.TextField()),
                ('pay_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'inquiries',
                'managed': False,
            },
        ),
    ]
